# Generated by Django 5.1.3 on 2025-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhnUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=True, max_length=128)),
                ('age', models.PositiveIntegerField(default=True)),
                ('address', models.TextField(default=True, max_length=255)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
