<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-02-25 10:51
=======
# Generated by Django 5.1.4 on 2025-02-25 10:54
>>>>>>> 0b287641e48f4376b0fcd6594b06c714903757e6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PhnUse',
=======
            name='PhnUser',
>>>>>>> 0b287641e48f4376b0fcd6594b06c714903757e6
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
<<<<<<< HEAD
                ('create_password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
=======
                ('password', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField()),
>>>>>>> 0b287641e48f4376b0fcd6594b06c714903757e6
                ('mobile_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
