# Generated by Django 5.1.4 on 2025-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='image',
            field=models.ImageField(default=True, upload_to='subdomain_images/'),
        ),
    ]
