# Generated by Django 5.1.4 on 2025-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phnuser',
            name='password',
        ),
        migrations.AddField(
            model_name='phnuser',
            name='address',
            field=models.TextField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phnuser',
            name='first_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phnuser',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='phnuser',
            name='last_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
