# Generated by Django 5.1.3 on 2025-02-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phnuser',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
