# Generated by Django 5.1.4 on 2025-02-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhnUse',
            new_name='PhnUser',
        ),
    ]
