# Generated by Django 5.1.3 on 2025-03-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_auto_20250306_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Eapp.technologydomain')),
            ],
        ),
    ]
