# Generated by Django 5.1.3 on 2025-03-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_alter_phnuser_address_alter_phnuser_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phnuser',
            old_name='gmail',
            new_name='email',
        ),
    ]
