# Generated by Django 5.1.4 on 2025-02-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_remove_phnuser_password_phnuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phnuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
