# Generated by Django 5.1.3 on 2025-03-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_rename_gmail_phnuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phnuser',
            old_name='email',
            new_name='gmail',
        ),
    ]
