# Generated by Django 5.1.4 on 2025-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_alter_phnuser_id_alter_project_id_alter_subdomain_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recommended', models.CharField(max_length=100)),
                ('customizable_options', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
