# Generated by Django 5.1.4 on 2025-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_phnuser_password_alter_phnuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phnuser',
            name='address',
            field=models.TextField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='age',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='phnuser',
            name='password',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
