# Generated by Django 5.1.3 on 2025-03-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0004_rename_email_phnuser_gmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phnuser',
            old_name='gmail',
            new_name='email',
        ),
    ]
