# Generated by Django 3.1.14 on 2025-03-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0004_auto_20250318_1223'),
        ('Eapp', '0004_component'),
    ]

    operations = [
    ]
