# Generated by Django 5.1.4 on 2025-03-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0004_auto_20250318_1223'),
        ('Eapp', '0004_component'),
    ]

    operations = [
    ]
