# Generated by Django 5.1.3 on 2025-02-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0004_alter_phnuser_address_alter_phnuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phnuser',
            name='gender',
        ),
    ]
