# Generated by Django 5.1.3 on 2025-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0004_auto_20250306_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phnuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='technologydomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
