# Generated by Django 5.1.4 on 2025-03-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0005_merge_0004_auto_20250318_1223_0004_component'),
        ('Eapp', '0005_merge_20250318_1530'),
    ]

    operations = [
    ]
