# Generated by Django 5.1.4 on 2025-03-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_subdomain_image'),
        ('Eapp', '0007_project_slug_alter_phnuser_id_alter_project_id_and_more'),
    ]

    operations = [
    ]
