# Generated by Django 5.1.4 on 2025-03-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0007_project_components_project_price_project_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='specifications',
        ),
    ]
