# Generated by Django 5.1.4 on 2025-03-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0006_merge_20250318_1604'),
        ('Eapp', '0008_remove_project_quantity_and_more'),
    ]

    operations = [
    ]
