# Generated by Django 5.1.4 on 2025-03-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0008_merge_20250310_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
        migrations.AddField(
            model_name='project',
            name='guide_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='guide_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='interface_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='interface_diagrams/'),
        ),
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='report_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='report_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Eapp.subdomain'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
