# Generated by Django 5.0.6 on 2025-03-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0009_merge_20250320_1406'),
        ('Eapp', '0010_alter_project_image'),
    ]

    operations = [
    ]
