# Generated by Django 5.1.4 on 2025-04-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0011_merge_20250326_1131'),
        ('Eapp', '0011_merge_20250326_1224'),
    ]

    operations = [
    ]
